trainings = [{
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-density-1k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_1000.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-density-2k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_2000.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-density-4k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_4000.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-density-8k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_8000.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-baseline",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-density-1k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_1000.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-density-2k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_2000.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-density-4k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_4000.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-density-8k",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_8000.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-baseline",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-force-33",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1/3,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-force-66",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 2/3,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-force-33",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1/3,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-force-66",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 2/3,
        "ball_mass": .1,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-mass-p3",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .3,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-mass-p5",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .5,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-mass-1",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": 1,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-DualArm-Attention-v0",
        "name": "dual-mass-2",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": 2,
        "model_path": "training_files/density_models/g1_dual_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-mass-p3",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .3,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-mass-p5",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": .5,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-mass-1",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": 1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-mass-2",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1,
        "ball_mass": 2,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-force-33",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 1/3,
        "ball_mass": 1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    {
        "task": "BallBalance-SingleArm-v0",
        "name": "single-force-66",
        "num_envs": 2048,
        "max_iterations": 500,
        "force_multiple": 2/3,
        "ball_mass": 1,
        "model_path": "training_files/density_models/g1_single_arm_baseline.xml",
    },
    ]